const jobsData = [
  {
    image: require("../Images/UI.png"),
    id: 1,
    Name: "UI/UX Designer",
    website: "Winbrans.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Top",
    Property: "New",
    Featured: "Yes",
    Published: "3month",
  },
  {
    image: require("../Images/Androiddev.png"),
    id: 1,
    Name: "Android Developer",
    website: "Infiniza.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Premium",
    Property: "New",
    Featured: "No",
    Published: "2month",
  },
  {
    image: require("../Images/SeniorM.png"),
    id: 1,
    Name: "Senior Manager",
    website: "Glovibo.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Featured",
    Featured: "Yes",
    Published: "1month",
  },
  {
    image: require("../Images/Product.png"),
    id: 1,
    Name: "Product Designer",
    website: "Bizotic.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Premium",
    Featured: "No",
    Published: "1month",
  },
  {
    image: require("../Images/Digital.png"),
    id: 1,
    Name: "Digital Marketer",
    website: "Topelzo.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Featured",
    Featured: "Yes",
    Published: "7month",
  },
  {
    image: require("../Images/Sales.png"),
    id: 1,
    Name: "Sales Manager",
    website: "Gotuzo.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Featured",
    Property: "New",
    Featured: "No",
    Published: "5month",
  },
  {
    image: require("../Images/WebDev.png"),
    id: 1,
    Name: "Web Developer",
    website: "Udiza.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Full Time",
    Property: "New",
    Featured: "Yes",
    Published: "2Year",
  },
  {
    image: require("../Images/SEO.png"),
    id: 1,
    Name: "SEO",
    website: "Oqata.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Premium",
    Property: "New",
    Featured: "No",
    Published: "1month",
  },
  {
    image: require("../Images/UI.png"),
    id: 1,
    Name: "UI/UX Designer",
    website: "Winbrans.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Full Time",
    Property: "New",
    Featured: "Yes",
    Published: "3month",
  },
  {
    image: require("../Images/Androiddev.png"),
    id: 1,
    Name: "Android Developer",
    website: "Infiniza.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Premium",
    Property: "New",
    Featured: "No",
    Published: "2month",
  },
  {
    image: require("../Images/SeniorM.png"),
    id: 1,
    Name: "Senior Manager",
    website: "Glovibo.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Featured",
    Featured: "Yes",
    Published: "1month",
  },
  {
    image: require("../Images/Product.png"),
    id: 1,
    Name: "Product Designer",
    website: "Bizotic.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Premium",
    Featured: "No",
    Published: "1month",
  },
  {
    image: require("../Images/Digital.png"),
    id: 1,
    Name: "Digital Marketer",
    website: "Topelzo.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Featured",
    Featured: "Yes",
    Published: "7month",
  },
  {
    image: require("../Images/Sales.png"),
    id: 1,
    Name: "Sales Manager",
    website: "Gotuzo.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Featured",
    Property: "New",
    Featured: "No",
    Published: "5month",
  },
  {
    image: require("../Images/WebDev.png"),
    id: 1,
    Name: "Web Developer",
    website: "Udiza.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Full Time",
    Property: "New",
    Featured: "Yes",
    Published: "2Year",
  },
  {
    image: require("../Images/SEO.png"),
    id: 1,
    Name: "SEO",
    website: "Oqata.com",
    salary: "$20k-$25k",
    location: "Location 210-27 Quadra, Market Street, Victoria Canada",
    time: "Premium",
    Property: "New",
    Featured: "No",
    Published: "1month",
  },
];

export default jobsData;
